vti_encoding:SR|utf8-nl
vti_author:SR|IFASDOM\\DAKHalsey
vti_timecreated:TR|05 Dec 2003 18:29:49 -0000
vti_modifiedby:SR|UFAD\\IF-ADMN-estragon
vti_backlinkinfo:VX|
vti_nexttolasttimemodified:TW|05 Dec 2003 18:31:59 -0000
vti_extenderversion:SR|5.0.2.4803
vti_timelastmodified:TR|15 Dec 2005 20:46:00 -0000
vti_syncwith_it-dakhalsey\:80/reporting:TR|05 Dec 2003 18:31:59 -0000
vti_lineageid:SR|{1E3F8303-A211-48FD-92A4-09FB6DEA6610}
vti_cacheddtm:TX|01 Apr 2004 20:48:35 -0000
vti_filesize:IR|508
