vti_encoding:SR|utf8-nl
vti_author:SR|IFASDOM\\DAKHalsey
vti_timecreated:TR|05 Dec 2003 18:27:43 -0000
vti_modifiedby:SR|UFAD\\IF-ADMN-estragon
vti_backlinkinfo:VX|
vti_nexttolasttimemodified:TW|15 Dec 2005 20:46:01 -0000
vti_extenderversion:SR|5.0.2.4803
vti_timelastmodified:TR|15 Dec 2005 20:48:42 -0000
vti_lineageid:SR|{6DD80C8D-9493-471E-8994-A417B0DECFB9}
vti_syncwith_it-dakhalsey\:80/reporting:TR|17 Nov 2004 18:56:10 -0000
vti_cacheddtm:TX|15 Dec 2005 20:48:42 -0000
vti_filesize:IR|6986
