vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|15 Dec 2005 20:46:05 -0000
vti_extenderversion:SR|5.0.2.4803
vti_lineageid:SR|{9E5F3F11-ABE7-41B0-AD8E-24124389252A}
vti_backlinkinfo:VX|
vti_author:SR|UFAD\\IF-ADMN-estragon
vti_modifiedby:SR|UFAD\\IF-ADMN-estragon
vti_nexttolasttimemodified:TW|05 Dec 2005 19:47:43 -0000
vti_timecreated:TR|15 Dec 2005 20:46:05 -0000
vti_cacheddtm:TX|05 Dec 2005 19:47:43 -0000
vti_filesize:IR|5668
