vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|15 Dec 2005 20:46:04 -0000
vti_extenderversion:SR|5.0.2.4803
vti_lineageid:SR|{6C39DD85-5A47-4291-B780-D61139E7DF24}
vti_backlinkinfo:VX|
vti_author:SR|UFAD\\IF-ADMN-estragon
vti_modifiedby:SR|UFAD\\IF-ADMN-estragon
vti_nexttolasttimemodified:TW|02 Dec 2005 22:08:05 -0000
vti_timecreated:TR|15 Dec 2005 20:46:04 -0000
vti_cacheddtm:TX|02 Dec 2005 22:08:05 -0000
vti_filesize:IR|5828
