vti_encoding:SR|utf8-nl
vti_author:SR|DAKHalsey
vti_timecreated:TR|01 Mar 2004 11:55:43 -0500
vti_modifiedby:SR|UFAD\\IF-ADMN-estragon
vti_backlinkinfo:VX|
vti_nexttolasttimemodified:TW|01 Mar 2004 16:55:43 -0000
vti_extenderversion:SR|5.0.2.4803
vti_timelastmodified:TR|15 Dec 2005 20:46:03 -0000
vti_syncwith_it-dakhalsey\:80/reporting:TR|01 Mar 2004 11:55:43 -0500
vti_lineageid:SR|{1CB74D35-22C4-4B28-86CF-77D1D4574F64}
vti_cacheddtm:TX|05 May 2004 13:59:29 -0000
vti_filesize:IR|5134
