vti_encoding:SR|utf8-nl
vti_author:SR|IFASDOM\\DAKHalsey
vti_modifiedby:SR|UFAD\\IF-ADMN-estragon
vti_timecreated:TR|05 Dec 2003 18:29:38 -0000
vti_timelastmodified:TR|15 Dec 2005 20:46:06 -0000
vti_extenderversion:SR|5.0.2.4803
vti_backlinkinfo:VX|
vti_nexttolasttimemodified:TW|05 Dec 2003 18:31:50 -0000
vti_syncwith_it-dakhalsey\:80/reporting:TR|05 Dec 2003 18:31:50 -0000
vti_lineageid:SR|{13A247CE-3ACD-4FB4-BC4F-4C8E6E424B92}
vti_cacheddtm:TX|15 Dec 2005 20:46:06 -0000
vti_filesize:IR|0
