                </tbody>
              </table>
            </div>
            <div style="clear:both;"></div>
          </div>
          <div style="clear:both;"></div>
        </div>
        <div style="clear:both;"></div>
        <div class="divider"></div>
        <div id="site-footer">
          <div id="funding">
            <img src="http://sare.thinkcreative.com/var/ezflow_site/storage/images/media-library/images/all-logos/national-sare-logo/sare-logo/1897-2-eng-US/SARE-logo_small.jpg" width="100" height="78"  style="" alt="SARE logo" title="SARE logo" />
            <img src="http://sare.thinkcreative.com/var/ezflow_site/storage/images/north-central-sare/north-central-footer/usda-logo/1925-4-eng-US/USDA-logo_small.jpg" width="100" height="69"  style="" alt="USDA Logo" title="USDA Logo" />
          </div><!-- funding -->
          <div id="footer-info">	
            <p>1122 Patapsco Building | University of Maryland | College Park, MD 20742-6715</p>	
            <p>This Web site is maintained by the national outreach office of the SARE program, supported by the National Institute of&nbsp;Food and Agriculture, U.S. Department of Agriculture.</p>	
            <p><a href="http://www.northcentralsare.org/" id="" title="" target="_self">North Central SARE</a>&nbsp;| <a href="http://nesare.org/" id="" title="" target="_self">Northeast SARE</a>&nbsp;| <a href="http://www.southernsare.org/" id="" title="" target="_self">Southern SARE</a>&nbsp;|&nbsp;<a href="http://www.westernsare.org/" id="" title="" target="_self">Western SARE</a></p>
          </div><!-- footer-info -->
          <div id="footer-menu">
            <p>Sustainable Agriculture Research &amp; Education &copy;2010</p>
            <ul class="menu horizontal">
			  <li>
                <a href="http://www.sare.org/Website-Help">Help</a>  |
              </li>
              <li>
                <a href="http://www.sare.org/Social-Media/RSS-Feeds">RSS Feeds</a>  |
              </li>
			  <li>
                <a href="http://www.sare.org/Newsroom/A-Guide-To-This-Site">A Guide To This Site</a>  
              </li>
            </ul>
          </div><!-- footer-menu -->
        </div>
      </div>
      <div style="clear:both;"></div>
    </div>
    <table>
      <tbody>
        <tr><td></td></tr>