<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
<base href="http://www.sare.org/">

  <meta content="text/html; charset=iso-8859-1" http-equiv="Content-Type">

  <meta content="sustainable,sustainable agriculture,soil,ecological,weed,IPM,SARE,cover crop,rotation,marketing,value-added,Sustainable Agriculture Network,weeds" name="keywords">

  <link href="http://www.sare.org/css/stylens.css" type="text/css" rel="STYLESHEET">

  <script type="text/javascript">
<!--
if (navigator.appName=="Netscape"){
var appme=navigator.appVersion;
appnum=appme.substring(0,1);
if (appnum>=5){
document.write('<link rel="STYLESHEET" type="text/css" href="/css/style.css">');
} else {
document.write('');
}
} else {
if(navigator.platform=="MacPPC"){
document.write('<link rel="STYLESHEET" type="text/css" href="/css/stylemac.css">');
} else {
document.write('<link rel="STYLESHEET" type="text/css" href="/css/style.css">');
}
} var url
function changepage(formObject)
{
url = formObject.options[formObject.options.selectedIndex].value;
if(url != "empty")
{
window.location = url;
url = "";
}
}
-->
  </script>
  <title>SARE Dynamic Content System: Resources From SARE Projects</title>


  <link rel="stylesheet" type="text/css" href="http://www.sare.org/events/calendar.css">

  <meta content="text/html; charset=ISO-8859-1" http-equiv="content-type">

  <link href="includes/stylens.css" rel="stylesheet" type="text/css">
  <link href="includes/calendar.css" rel="stylesheet" type="text/css">
</head>


<body>

<!--header--><a name="top" id="top"></a>
<table border="0" cellpadding="0" cellspacing="0" width="100%">

  <tbody>

    <tr>

      <td bgcolor="#344e78" height="14"><a href="#content"><img src="http://www.sare.org/images/x.gif" alt="Skip to page content" border="0" height="1" width="1"></a></td>

    </tr>

    <tr>

      <td bgcolor="#dcd9bd" height="1"></td>

    </tr>

    <tr>

      <td background="http://www.sare.org/images/photoback.jpg" height="31"><a href="#nav"><img src="http://www.sare.org/images/x.gif" alt="Skip to navigation" border="0" height="1" width="1"></a></td>

    </tr>

    <tr>

      <td bgcolor="#dcd9bd" height="1"></td>

    </tr>

    <tr>

      <td class="small" align="center" bgcolor="#fafce8" height="57" valign="top"><a href="http://www.sare.org/index.htm"><img src="http://www.sare.org/images/header.gif" alt="Sustainable Agriculture Research and Education" border="0" height="36" width="587"></a><br>

      <a href="http://www.sare.org/about/index.htm">Grants and outreach to advance sustainable innovations to the whole of American agriculture.</a> </td>

    </tr>

    <tr>

      <td>
      <table bgcolor="#f6f8de" border="0" cellpadding="0" cellspacing="0" width="100%">

        <tbody>

          <tr>

            <td>
            <table border="0" cellpadding="0" cellspacing="0" width="100%">

              <tbody>

                <tr>

                  <td class="topnav" align="center"><img id="sizeimg1" name="sizeimg1" src="http://www.sare.org/images/x.gif" alt="" border="0" height="1" width="100%"><br>

                  <a href="http://www.sare.org/about/">About
Us</a></td>

                </tr>

              </tbody>
            </table>

            </td>

            <td bgcolor="#bfbca0" width="1"><img src="http://www.sare.org/images/x.gif" alt="" border="0" height="1" width="1"></td>

            <td>
            <table border="0" cellpadding="0" cellspacing="0" width="100%">

              <tbody>

                <tr>

                  <td class="topnav" align="center"><img id="sizeimg2" name="sizeimg2" src="http://www.sare.org/images/x.gif" alt="" border="0" height="1" width="100%"><br>

                  <a href="http://www.sare.org/grants/index.htm">Get
a
Grant</a></td>

                </tr>

              </tbody>
            </table>

            </td>

            <td bgcolor="#bfbca0" width="1"><img src="http://www.sare.org/images/x.gif" alt="" border="0" height="1" width="1"></td>

            <td>
            <table border="0" cellpadding="0" cellspacing="0" width="100%">

              <tbody>

                <tr>

                  <td class="topnav" align="center"><img id="sizeimg3" name="sizeimg3" src="http://www.sare.org/images/x.gif" alt="" border="0" height="1" width="100%"><br>

                  <a href="http://www.sare.org/projects/">Project
Reports</a></td>

                </tr>

              </tbody>
            </table>

            </td>

            <td bgcolor="#bfbca0" width="1"><img src="http://www.sare.org/images/x.gif" alt="" border="0" height="1" width="1"></td>

            <td>
            <table border="0" cellpadding="0" cellspacing="0" width="100%">

              <tbody>

                <tr>

                  <td class="topnav" align="center"><img id="sizeimg4" name="sizeimg4" src="http://www.sare.org/images/x.gif" alt="" border="0" height="1" width="100%"><br>

                  <a href="http://www.sare.org/highlights/index.htm">Highlights</a></td>

                </tr>

              </tbody>
            </table>

            </td>

            <td bgcolor="#bfbca0" width="1"><img src="http://www.sare.org/images/x.gif" alt="" border="0" height="1" width="1"></td>

            <td>
            <table border="0" cellpadding="0" cellspacing="0" width="100%">

              <tbody>

                <tr>

                  <td class="topnav_on" align="center"><img id="sizeimg5" name="sizeimg5" src="http://www.sare.org/images/x.gif" alt="" border="0" height="1" width="100%"><br>

                  <a href="http://www.sare.org/events/">Events</a></td>

                </tr>

              </tbody>
            </table>

            </td>

            <td bgcolor="#bfbca0" width="1"><img src="http://www.sare.org/images/x.gif" alt="" border="0" height="1" width="1"></td>

            <td>
            <table border="0" cellpadding="0" cellspacing="0" width="100%">

              <tbody>

                <tr>

                  <td class="topnav" align="center"><img id="sizeimg6" name="sizeimg6" src="http://www.sare.org/images/x.gif" alt="" border="0" height="1" width="100%"><br>

                  <a href="http://www.sare.org/publications/index.htm">Publications</a></td>

                </tr>

              </tbody>
            </table>

            </td>

          </tr>

        </tbody>
      </table>

      </td>

    </tr>

    <tr>

      <td bgcolor="#f1f5d2" height="1"><img src="http://www.sare.org/images/x.gif" alt="" border="0" height="1" width="1"></td>

    </tr>

    <tr>

      <td bgcolor="#b2ab9e"><img id="sizeimg" name="sizeimg" src="http://www.sare.org/images/x.gif" alt="" border="0" height="1" width="100%"></td>

    </tr>

  </tbody>
</table>
<table border="0" cellpadding="0" cellspacing="0" width="100%"><tbody><tr><td class="leftnav" style="width: 159px; vertical-align: top;">