<table align="center" width="760" cellspacing="0" cellpadding="8" border="0">

<tr>
	<td width="230" valign="top" bgcolor="D1CEB6">
	<div align="center"><img src="http://wsare.usu.edu/pics/lpic_4.jpg" width="200" border="0" alt="WSARE"></div>

	<ul>
	<li><a href="http://wsare.usu.edu/about/docs/simplysustainable.pdf">Simply Sustainable</a><br>
	<li><a href="/resource/resviewer.aspx">SARE Publications</a><br>
	<li>Sustainable Ag Resources: Videos, Handbooks, etc.
	<br><br>

	<li><a href="http://wsare.usu.edu/pub/pdf/PDSurveyRep04.pdf">2004 PDP Regional<br>Survey Report</a><br>
	<li><a href="http://wsare.usu.edu/pub/pdf/PDStateRep04.pdf">2004 PDP State-by-State<br>Survey Report</a><br>
	<li><a href="http://wsare.usu.edu/pub/sare2000/">2000 SARE Conference Proceedings</a><br>
	<li><a href="http://wsare.usu.edu/pub/pdf/AnnRep99.pdf">1999 Annual Report</a>
	<br><br>
	<li><a href="http://wsare.usu.edu/pub/index.cfm?sub=mktsearch">Farm-Direct Marketing Guide</a>

	</ul>


	</td>
	<td valign="top" bgcolor="F6F8DE" width="530">