<p>
	<span class="pagetitledown">SARE-Funded Projects</span>
<!--
	<br>
		<span class="boldblue">
			View/Edit/Approve Proposals</span>
	<br>
-->
		<br>
	View/Edit/Approve Reports
	<span class="boldblue">
		<ul>
		<li>Edit and Approve Reports Pending Approval</li>
		<li>Review Recently Approved Reports</li>
	</ul>
	</span>
	View/Edit/Approve Projects
	<span class="boldblue">
		<ul>
		<li>Recently Edited Projects</li>
		<li>All Projects</li>
		<li>Projects Lacking Reports</li>
	</ul>
	</span>
	<span class="boldblue">Assign PI to Existing Project</span>
	<br>
		<span class="boldblue">
			Search Projects</span><br>
	<span class="boldblue">Search Projects by Profile</span>
	<br>
	<span class="boldblue">Create Project</span>
</p>