<p>
	<span class="pagetitledown">Resources</span>
	<br>
	View/Edit/Approve Resource Entries
	<span class="boldblue">
		<ul>
		<li>Edit and Approve Resources Pending Approval</li>
		<li>Review Recently Approved Resource Entries</li>
	</ul>
	</span>
	View/Edit/Approve Resource Compilations
	<span class="boldblue">
		<ul>
		<li>Compilations Pending Approval</li>
		<li>Compilations You Manage</li>
	</ul>
	</span>
		<span class="boldblue">
			Search Resources</span>
	<br>
	<span class="boldblue">Search Resources by Profile</span>
	<br>
	<span class="boldblue">Create Resource Entry</span>
	<br>
	<span class="boldblue">Create Resource Compilation</span>
	<br>
	<span class="boldblue">List all Resources You Manage</span>
</p>