<p>
	<span class="pagetitledown">User Accounts</span>
	<br /><br />
		<a href="?do=userlist">User Account Management</a>
<!--
		<a href="?do=userlist">View New and Changed Accounts</a>
	<br>
		<a href="?do=userlist">Search and Manage User Accounts, Roles, and Data Ownership</a>
	<br>
	<span class="boldblue">Export user information</span>
	<br>
	<span class="boldblue">Create New Account</span>
-->
</p>