<p>
	<table style="text-align: left; width: 100%;" border="0" cellpadding="0" cellspacing="0">
		<tbody>
			<tr>
				<td><span class="pagetitledown">My SARE Projects</span></td>
				<td><span class="boldblue alright">About SARE Projects</span></td>
			</tr>
		</tbody>
	</table>
<!--
<br>
	Input New Project Information<br>
	<br>
	Create Annual/Final Report<br>
	<br>
-->
	<a href="?do=grants">View/Edit My Projects and Reports</a><br>
	<ul>
		<li>Unfinished Reports</li>
		<li>Reports Pending Approval</li>
		<li>Recently Approved Reports</li>
		<li>General Project Information &amp; Contacts</li>
	</ul>
</p>