<table style="text-align: left; width: 100%;" border="0" cellpadding="4" cellspacing="0">

        <tbody>
          <tr>
            <td><span class="pagetitledown">My&nbsp;</span><span class="boldblue"></span><span class="pagetitledown">Resources</span></td>
            <td><span class="boldblue alright">About Resources</span></td>
          </tr>
        </tbody>
      </table>
      <span class="pagetitledown"></span><span style="font-style: italic;"></span><span style="font-style: italic;"></span><span style="font-style: italic;"></span><span class="boldblue"></span><span class="pagetitledown"></span><br>
      <span class="boldblue">Add New Resource<br>
      <br>
      </span>

		  <span class="boldblue">
			  View/Edit My Resources</span>
		  <span style="font-style: italic;"></span><span style="font-style: italic;">


      </span>
      
      <ul>


        <li>Resources Pending Approval</li>


        <li>Recently Approved Resources</li>


      
      </ul>