<p>
	<span class="pagetitledown">SARE-Funded Projects</span>
<!--
	<br>
		<span class="boldblue">
			View/Edit/Approve Proposals in Your Region</span>
	<br>
-->
	<br>
	View/Edit/Approve Reports in Your Region
	<span class="boldblue">
		<ul>
		<li>Edit and Approve Reports Pending Approval</li>
		<li>Review Recently Approved Reports</li>
	</ul>
	</span>
	View/Edit/Approve Projects in Your Region
	<span class="boldblue">
		<ul>
		<li>Recently Edited Projects</li>
		<li>All Projects</li>
		<li>Projects Lacking Reports</li>
	</ul>
	</span>
		<span class="boldblue">
			Search Projects</span><br>
	<span class="boldblue">Search Projects by Profile</span>
	<br>
	<span class="boldblue">Create Project</span>
</p>